config/routes.rb
Rails.application.routes.draw do
	root :to => "gambars#index"
	resources :gambars

end

app/models/gambar.rb
class Gambar < ActiveRecord::Base
	validates :title, presence: true,
                    length: { minimum: 3 }
    has_attached_file :nama_gambar, :styles=>{:medium=>"400x200>", :thumb=>"200x100>", :default_url=>""}
    validates_attachment_content_type :nama_gambar, :content_type =>/\Aimage\/.*\Z/
    validates :nama_gambar, presence:true;
    validates_attachment_size :nama_gambar, :less_than=>200.kilobytes 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/gambars_controller.rb
class GambarsController < ApplicationController
  def index
    @gambars = Gambar.all
  end

  def new
    @gambar = Gambar.new
  end

  def create
    @gambar = Gambar.new(params_gambar)
    if @gambar.save
      flash[:notice] = "Success Add Records"
      redirect_to action: 'index'
    else flash[:error] = "Data not valid"
    	render 'new'
    end
  end

  def show
    @gambar = Gambar.find_by_id(params[:id])
  end

  def edit
    @gambar = Gambar.find_by_id(params[:id])
  end

  def update
    @gambar = Gambar.find_by_id(params[:id])
    if @gambar.update(params_gambar)
      flash[:notice] = "Success Update Records"
      redirect_to action: 'index'
    else
      flash[:error] = "data not valid"
      render 'edit'
    end
  end

  def destroy
    @gambar = Gambar.find_by_id(params[:id])
    if @gambar.destroy
      flash[:notice] = "Success Delete a Records"
      redirect_to action: 'index'
    else
      flash[:error] = "fails delete a records"
      redirect_to action: 'index'
    end
  end

  private 
  def params_gambar
      params.require(:gambar).permit(:title,:nama_gambar)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/gambars/edit.html.erb
<%= form_for @gambar do |g| %>
<%= g.label :title %>
<%= g.text_field :title %>
<br/>
<%= g.file_field :nama_gambar %>
<%= @gambar.errors[:nama_gambar].first unless @gambar.errors[:nama_gambar].blank?%>
<br/>
<%= g.submit :submit %>
<% end %>
<div>
<%= link_to "back to index", gambars_path,:class=>"Nav" %>
</div>	

app/views/gambars/index.html.erb
 <% @gambars.each do |gambar| %>
    <h3 id="judul"><%= gambar.title %></h3>
    <p>
    <%= link_to (image_tag gambar.nama_gambar.url(:thumb)), gambar_path(gambar)  %><br>
     
    </p>
	<span><%= link_to 'edit', edit_gambar_path(gambar.id),:class=>"Nav" %><span>
	<span> | </span>
	<span><%= link_to 'delete', gambar_path(gambar.id),:class=>"Nav", method: "DELETE", data:
	{confirm: 'Delete this data ? '} %><span>
	</p>
    <hr/>
  <% end %>

app/views/gambars/new.html.erb
<%= form_for @gambar do |f| %>
   <%= f.label :title %>
   <%= f.text_field :title %>
   <%= @gambar.errors[:title].first unless @gambar.errors[:title].blank? %>
   <br/>
   <%= f.file_field :nama_gambar %>
   <%= @gambar.errors[:nama_gambar].first unless @gambar.errors[:nama_gambar].blank?%>
   <br/>
   <%= f.submit :submit %>
  <% end %>

app/views/gambars/show.html.erb
<h3><%= @gambar.title %></h3>
 <%= link_to (image_tag @gambar.nama_gambar.url(:medium)), gambar_path(@gambar) %><br>
<p><%= link_to 'back to index', gambars_path,:class=>"Nav" %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tugas4</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="application.css" rel="stylesheet" type="text/css"/>
</head>
<body>
<UL>
  	<li><%= link_to 'HOME', gambars_path(), :class=>"Nav"%></li>
  	<li><%= link_to 'UPLOAD GAMBAR', new_gambar_path(), :class=>"Nav" %></li>
  </UL>
  <hr/>
<%= yield %>

</body>
</html>